<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.26" />
    <PackageReference Include="Syncfusion.Chart.Windows" Version="31.2.15" />
    <PackageReference Include="Syncfusion.Core.WinForms" Version="31.2.15" />
    <PackageReference Include="Syncfusion.Schedule.Windows" Version="31.2.15" />
    <PackageReference Include="Syncfusion.SfDataGrid.WinForms" Version="31.2.15" />
    <PackageReference Include="Syncfusion.SfInput.WinForms" Version="31.2.15" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="31.2.15" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="31.2.15" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="WinForms\Inputs\InputNUD.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="WinForms\Inputs\InputDTP.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="WinForms\Inputs\InputCMB.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
